### ISSUE TITLE
There is issue with controllers reading on some Famicom

### ISSUE THREAD

**Issue by kolmogorovpavel** [g0me3/greenberret_fds#2]
When game started from UNROM cartridge (not reproduced with Everdrive N8) on AV Famicom then button START doesn't work, button A works like SELECT.
The same cartridge works fine on famiclone. So maybe issue related to timings.
Can be reproduced in Nestopia 1.40.

**Comment by g0me3** [comment]
try latest rev if it work

**Comment by kolmogorovpavel** [comment]
Issue is resolved.
